# CI/CD Configuration
environments:
  staging:
    name: Staging Environment
    url: https://staging.example.com
    protection_rules:
      - required_reviewers: 1
      - wait_timer: 5
    
  production:
    name: Production Environment
    url: https://production.example.com
    protection_rules:
      - required_reviewers: 2
      - wait_timer: 10

# Test Configuration
test:
  python_versions: [3.9, 3.10, 3.11]
  coverage_threshold: 80
  security_scan: true
  performance_test: true

# Build Configuration
build:
  platforms: [linux/amd64, linux/arm64]
  cache: true
  registry: ghcr.io
  tags:
    - latest
    - ${{ github.sha }}
    - ${{ github.ref_name }}

# Deployment Configuration
deployment:
  staging:
    replicas: 2
    resources:
      cpu: "500m"
      memory: "1Gi"
  
  production:
    replicas: 3
    resources:
      cpu: "1000m"
      memory: "2Gi"

# Notification Configuration
notifications:
  slack_webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
  email: ${{ secrets.NOTIFICATION_EMAIL }}
  teams_webhook: ${{ secrets.TEAMS_WEBHOOK_URL }}

# Security Configuration
security:
  bandit_severity: medium
  bandit_confidence: medium
  dependency_check: true
  container_scan: true

# Performance Configuration
performance:
  locust_users: 10
  locust_spawn_rate: 1
  locust_run_time: 60s
  acceptable_response_time: 2000ms 